### ISSUE TITLE
Unexpected connection pool behavior

### ISSUE THREAD

**Issue by bissaias** [vert-x3/vertx-mysql-postgresql-client#10] opened 2015-03-09 19:46 UTC
I came across a weird problem with the MySQL connection pool. First of all, while I set the `maxPoolSize` configuration option to 1, I see that mysql-service after a few queries creates and maintains not 1 but 4 connections to the server (I am counting the connections of user vertx as seen from MySQL Workbench).

Additionally, I am getting wrong results when using the `COUNT` aggregation function in 50% of my queries. It seems that when the result is wrong, a cached version of the query is returned which is however wrong because the number of rows in the table has changed since then. A proof to that assumption is the fact that the problem is resolved whenever I manually kill the connections of user vertx using MySQL Workbench. Practically this forces mysql-service to repopulate the connection pool with fresh connections. From that point on the `COUNT` queries work as expected. Please note that MySQL `query_cache_size` is set to 0 during this behavior.

**Comment by Narigo** [comment] 2015-03-10 09:00
Would it be possible for you to write a test for this issue somehow?
You should be able to use Java or whatever Vert.x 3 language you prefer.. :)

**Comment by bissaias** [comment] 2015-03-10 09:36
I was afraid you would ask something like this :-}
I believe that the first part of the problem (`maxPoolSize` differs from actual connections) is something you can test yourself.
I will try to replicate the second part of the problem in a test and send it over via a pull request.

**Comment by Narigo** [comment] 2015-03-10 09:45
Thank you for taking the time :)

**Comment by purplefox** [comment] 2015-05-26 12:28
Any updates on this?

**Comment by purplefox** [comment] 2015-06-18 14:50
@narigo did you investigate this? E.g. checking maxPoolsize compared to number of connections?

**Comment by purplefox** [comment] 2015-06-19 09:38
Does anyone have any updates on this? Cheers

We need to decide very soon if this client is going to make it into the 3.0 release or not.

**Comment by Narigo** [comment] 2015-06-19 09:54
Sorry, this missed my attention. Won't be able to have a look at it this week or the next. If I'd get a test from @bissaias I might be able to find a few minutes on sunday...?

**Comment by purplefox** [comment] 2015-06-21 17:21
I'm guessing this bug could be due to the fact that the client does not appear to be threa d safe at all as reported here https://github.com/vert-x3/vertx-mysql-postgresql-client/issues/20

Based on this I am not confident that this client is stable enough to be used in production as yet, so I think we should drop it from the 3.0 release.

**Comment by pmlopes** [comment] 2016-01-19 19:08
We'll close this issue since it referred to the old Scala implementation and there was no reproducer provided. If in the future it re-appears it should be reopened.

**Closed by pmlopes** 2016-01-19 19:08 UTC
Labels: deferred
