### ISSUE TITLE
query/queryStream/update handlers invoked again if they throw an exception

### ISSUE THREAD

**Issue by omar753sahl** [vert-x3/vertx-mysql-postgresql-client#104] opened 2018-02-08 03:17 UTC
The method below prints out "Successful insertion" and "Insertion failed".
Am I missing something or is it a normal behavior?

```java
private void insert(Movie movie, SQLConnection connection, Handler<AsyncResult<Movie>> next) {
        String sql = "INSERT INTO Movies (name, release) VALUES (?, ?)";
        JsonArray json = new JsonArray().add(movie.getName()).add(movie.getRelease());

        connection.updateWithParams(
            sql,
            json,
            (asyncResult) -> {
                if (asyncResult.succeeded()) {
                    System.out.println("Successful insertion");
                }

                if (asyncResult.failed()) {
                    System.out.println("Insertion failed");
                    next.handle(Future.failedFuture(asyncResult.cause()));
                    return;
                }

                UpdateResult result = asyncResult.result();
                Movie m = new Movie(result.getKeys().getInteger(0), movie.getName(), movie.getRelease());
                next.handle(Future.succeededFuture(m));
            }
        );
    }
```

**Comment by tsegismont** [comment] 2018-02-08 09:48
No it's not normal behavior. Can you put together a small reproducer?
POM/Gradle file, verticle source, Docker command to setup the database (or
in memory with H2/HSQL)

2018-02-08 4:17 GMT+01:00 Omar Sahl <notifications@github.com>:

**Comment by omar753sahl** [comment] 2018-02-08 15:14
Sure, 
Here's the **pom.xml**
```xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.os</groupId>
    <artifactId>VertxMavenPlayground</artifactId>
    <version>1.0.0-SNAPSHOT</version>

    <properties>
        <java.version>1.8</java.version>
        <vertx.version>3.5.0</vertx.version>
    </properties>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.5.1</version>
                <configuration>
                    <source>${java.version}</source>
                    <target>${java.version}</target>
                </configuration>
            </plugin>

            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-shade-plugin</artifactId>
                <version>2.4.3</version>
                <executions>
                    <execution>
                        <phase>package</phase>
                        <goals>
                            <goal>shade</goal>
                        </goals>
                        <configuration>
                            <transformers>
                                <transformer
                                    implementation="org.apache.maven.plugins.shade.resource.ManifestResourceTransformer">
                                    <manifestEntries>
                                        <Main-Class>io.vertx.core.Launcher</Main-Class>
                                        <Main-Verticle>com.os.VertxMavenPlayground.MainVerticle</Main-Verticle>
                                    </manifestEntries>
                                </transformer>
                                <transformer
                                    implementation="org.apache.maven.plugins.shade.resource.AppendingTransformer">
                                    <resource>META-INF/services/io.vertx.core.spi.VerticleFactory</resource>
                                    <resource>META-INF/services/io.vertx.core.spi.launcher.CommandFactory</resource>
                                </transformer>
                            </transformers>
                            <artifactSet>
                            </artifactSet>
                            <outputFile>${project.build.directory}/${project.artifactId}-${project.version}-fat.jar
                            </outputFile>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

    <dependencies>

        <dependency>
            <groupId>io.vertx</groupId>
            <artifactId>vertx-unit</artifactId>
            <version>${vertx.version}</version>
        </dependency>

        <dependency>
            <groupId>io.vertx</groupId>
            <artifactId>vertx-core</artifactId>
            <version>${vertx.version}</version>
        </dependency>

        <dependency>
            <groupId>io.vertx</groupId>
            <artifactId>vertx-web</artifactId>
            <version>${vertx.version}</version>
        </dependency>

        <dependency>
            <groupId>io.vertx</groupId>
            <artifactId>vertx-mysql-postgresql-client</artifactId>
            <version>${vertx.version}</version>
        </dependency>

        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-api</artifactId>
            <version>1.7.25</version>
        </dependency>

        <dependency>
            <groupId>org.postgresql</groupId>
            <artifactId>postgresql</artifactId>
            <version>42.2.1</version>
        </dependency>
    </dependencies>

</project>
```
And here's the **verticle code**:
```java
public class MainVerticle extends AbstractVerticle {

    private SQLClient jdbc;

    @Override
    public void start(Future<Void> fut) throws Exception {
        jdbc = PostgreSQLClient.createShared(vertx, getDbConf(), "movies-collection");

        startBackend(
            (connection) ->
                createData(connection,
                    (nothing) -> startApp(
                        (http) -> completeStartApp(http, fut)
                    ), fut
                ), fut
        );
    }

    @Override
    public void stop() throws Exception {
        jdbc.close();
        super.stop();
    }

    private void startBackend(Handler<AsyncResult<SQLConnection>> next, Future<Void> fut) {
        jdbc.getConnection(ar -> {
            if (ar.failed()) {
                fut.fail(ar.cause());
            } else {
                next.handle(Future.succeededFuture(ar.result()));
            }
        });
    }

    private void startApp(Handler<AsyncResult<HttpServer>> next) {
        Router router = Router.router(vertx);

        router.route("/").handler(routingContext -> {
            HttpServerResponse response = routingContext.response();
            response
                .putHeader("content-type", "text/html")
                .end("<h1>Movies Collection App</h1>");
        });

        router.route("/assets/*").handler(StaticHandler.create("assets"));
        router.get("/api/movies").handler(this::getAll);
        router.route("/api/movies/*").handler(BodyHandler.create());
        router.post("/api/movies").handler(this::addOne);

        vertx
            .createHttpServer()
            .requestHandler(router::accept)
            .listen(
                Integer.getInteger("http.port", 8080),
                System.getProperty("http.address", "0.0.0.0"),
                next
            );
    }

    private void completeStartApp(AsyncResult<HttpServer> httpServer, Future<Void> fut) {
        if (httpServer.succeeded()) {
            fut.complete();
            System.out.println("Started the server!");
        } else {
            fut.fail(httpServer.cause());
        }
    }

    private void createData(AsyncResult<SQLConnection> asyncResult, Handler<AsyncResult<Void>> next, Future<Void> fut) {
        if (asyncResult.failed()) {
            fut.fail(asyncResult.cause());
        } else {
            SQLConnection connection = asyncResult.result();
            connection.execute(
                "CREATE TABLE IF NOT EXISTS Movies (id SERIAL, name varchar(100), release varchar(10))",
                ar -> {
                    if (ar.failed()) {
                        System.out.println("Failed at creating data!!");
                        fut.fail(ar.cause());
                    }
                    next.handle(Future.succeededFuture());
                    connection.close();
                });
        }
    }

    private void getAll(RoutingContext context) {
        jdbc.getConnection(ar -> {
            SQLConnection connection = ar.result();
            connection.query("SELECT * FROM Movies", result -> {
                List<Movie> movies = result.result().getRows().stream().map(Movie::new).collect(Collectors.toList());
                System.out.println("getAll returns " + movies.size() + " movie(s)");
                context.response()
                    .putHeader("content-type", "application/json; charset=utf-8")
                    .end(Json.encodePrettily(movies));
                connection.close();
            });
        });
    }

    private void addOne(RoutingContext context) {
        jdbc.getConnection(ar -> {
            Movie movie = Json.decodeValue(context.getBodyAsString(), Movie.class);
            System.out.println("addOne: got " + movie.toString());
            SQLConnection connection = ar.result();
            insert(movie, connection, result -> {
                System.out.println("addOne: got " + movie + ", returning " + result.result());
                context.response()
                    .setStatusCode(201)
                    .putHeader("content-type", "application/json; charset=utf-8")
                    .end(Json.encodePrettily(result.result()));
            });
            connection.close();
        });
    }

    private void insert(Movie movie, SQLConnection connection, Handler<AsyncResult<Movie>> next) {
        String sql = "INSERT INTO Movies (name, release) VALUES (?, ?)";
        JsonArray json = new JsonArray().add(movie.getName()).add(movie.getRelease());

        connection.updateWithParams(
            sql,
            json,
            (asyncResult) -> {
                if (asyncResult.succeeded()) {
                    System.out.println("Successful insertion");
                }

                if (asyncResult.failed()) {
                    System.out.println("insert: failed at inserting (" + json + ")" + " >>> " + asyncResult.cause().getMessage());
                    next.handle(Future.failedFuture(asyncResult.cause()));
                    return;
                }

                UpdateResult result = asyncResult.result();
                Movie m = new Movie(result.getKeys().getInteger(0), movie.getName(), movie.getRelease());
                next.handle(Future.succeededFuture(m));
            }
        );
    }

    private JsonObject getDbConf() throws URISyntaxException {
        URI dbUri = new URI(System.getenv("DATABASE_URL"));

        System.out.println("DB Uri: " + dbUri.toString());

        String username = dbUri.getUserInfo().split(":")[0];
        String password = dbUri.getUserInfo().split(":")[1];

        JsonObject config = new JsonObject();
        config.put("url", "jdbc:postgresql://" + dbUri.getHost() + ":" + dbUri.getPort() + "/" + "moviesDb");
        config.put("username", username);
        config.put("password", password);
        config.put("database", dbUri.getPath().split("/")[1]);
        config.put("driver_class", "org.postgresql.Driver");
        return config;
    }
}
```
And here's the **Movie** bean class:
```java
public class Movie {
    private final int id;

    private String name;

    private String release;

    public Movie(JsonObject json) {
        this.id = json.getInteger("id");
        this.name = json.getString("name");
        this.release = json.getString("release");
    }

    public Movie(int id, String name, String release) {
        this.id = id;
        this.name = name;
        this.release = release;
    }

    public Movie(String name, String release) {
        this.id = -1;
        this.name = name;
        this.release = release;
    }

    public Movie() {
        this.id = -1;
    }

    public String getName() {
        return name;
    }

    public String getRelease() {
        return release;
    }

    public int getId() {
        return id;
    }

    public void setName(String name) {
        this.name = name;
    }

    public void setRelease(String release) {
        this.release = release;
    }

    @Override
    public String toString() {
        return "Movie{" +
            "id=" + id +
            ", name='" + name + '\'' +
            ", release='" + release + '\'' +
            '}';
    }
}
```
BTW, I'm not using Docker, I have a postgres server running on my computer.

**Comment by tsegismont** [comment] 2018-02-12 16:56
Got some time to look into your problem. Here are my findings.

1/ This module does not return generated keys yet.
There is a PR (#91) but it hasn't been merged yet (missing tests). Consequently, your handler throws an exception at `result.getKeys().getInteger(0)`.

2/ The Scala future adapter may invoke the handler again if a first invocation throws an exception.
The code is in `io.vertx.ext.asyncsql.impl.AsyncSQLConnectionImpl#handleAsyncUpdateResultToResultSet`:

```java
    return ar -> {
      if (ar.succeeded()) {
        try {
         // handler is called here first and throws exception (out of bounds for getKeys().getInteger(0))
          handler.handle(Future.succeededFuture(queryResultToUpdateResult(ar.result())));
        } catch (Throwable e) {
          // exception is caught and handler invoked again
          handler.handle(Future.failedFuture(e));
        }
      } else {
        handler.handle(Future.failedFuture(ar.cause()));
      }
    };
```

I believe this code is wrong. If the handler throws a `RuntimeException`, so be it. The try/catch should only wrap the `queryResultToUpdateResult` call.

**Comment by omar753sahl** [comment] 2018-02-12 17:05
Thank you @tsegismont for your help.
So I got the problem now. However, should I wait for this bug to get fixed or Is there any workaround to get the inserted row id?

**Comment by tsegismont** [comment] 2018-02-12 17:24
@omar753sahl depends on your project schedule. I'm going to work on these issues this week but, even if changes get merged soon, they won't be another release in the following weeks.

So you can either:
1/ build your own version of the module when the changes are ready
2/ use a workaround

Workarounds
1/ invoke `nextval` for your sequence before inserting (and manually set the id)
OR
2/ execute  `SELECT currval('movies_id_seq')` just after insert  (docs says it is safe per session, so it should work as long as do it with the same connection)

**Comment by tsegismont** [comment] 2018-02-13 21:46
@omar753sahl I looked into #91 but the fix is wrong. But I found the solution to your problem.

Change your query to "INSERT INTO Movies (name, release) VALUES (?, ?) RETURNING id" and call `connection.queryWithParams` instead of `connection.updateWithParams`. The code looks like this:

```java
    String sql = "INSERT INTO Movies (name, release) VALUES (?, ?) returning id";
    JsonArray json = new JsonArray().add(movie.getName()).add(movie.getRelease());

    connection.queryWithParams(
        sql,
        json,
        (asyncResult) -> {

          System.out.println("blam");

          if (asyncResult.succeeded()) {
            System.out.println("Successful insertion");
          }

          if (asyncResult.failed()) {
            asyncResult.cause().printStackTrace();
            System.out.println("insert: failed at inserting (" + json + ")" + " >>> " + asyncResult.cause().getMessage());
            next.handle(Future.failedFuture(asyncResult.cause()));
            return;
          }

          ResultSet result = asyncResult.result();
          System.out.println("result = " + result.toJson());
          Movie m = new Movie(result.getResults().get(0).getInteger(0), movie.getName(), movie.getRelease());
          next.handle(Future.succeededFuture(m));
        }
    );
```

**Closed** 2018-02-20 21:28 UTC
Labels: to review

**Comment by Narigo** [comment] 2018-02-20 21:29
Thanks a lot for reporting and the PR to all of you! :)
